# Generated by Django 4.0.3 on 2022-08-02 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='sales',
        ),
        migrations.RemoveField(
            model_name='salesperson',
            name='sales',
        ),
    ]
