# Generated by Django 4.0.3 on 2022-08-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0006_alter_customer_phonenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesperson',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
