# Generated by Django 4.0.3 on 2022-08-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0007_alter_salesperson_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesperson',
            name='employeeNumber',
            field=models.PositiveBigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
