# Generated by Django 4.0.3 on 2022-08-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0008_alter_salesperson_employeenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilevo',
            name='sold',
            field=models.BooleanField(null=True),
        ),
    ]
