# Generated by Django 4.0.3 on 2022-08-03 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0010_alter_automobilevo_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='auto',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='sales_rest.automobilevo'),
        ),
    ]
