# Generated by Django 4.0.3 on 2022-08-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='vin',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='automobilevo',
            name='vin',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='vin',
            field=models.TextField(),
        ),
    ]
