# Generated by Django 4.0.3 on 2022-08-04 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_alter_appointments_vin_alter_automobilevo_vin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='auto',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='service_rest.automobilevo'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='technician',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='service_rest.technician'),
        ),
    ]
