# Generated by Django 4.0.3 on 2022-08-04 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_appointments_auto_alter_appointments_technician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='auto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='service_rest.automobilevo'),
        ),
    ]
