# Generated by Django 4.0.3 on 2022-08-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_rest', '0003_alter_automobile_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobile',
            name='returning',
            field=models.BooleanField(default=False),
        ),
    ]
